import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import CardsOne from "@/components/cards";
import cofeeshopeData from "../data/cofee-shope.json";

//this part is a server side part
export async function getStaticProps(context) {
  console.log("context :", context);
  return {
    props: {
      cofeeshope: cofeeshopeData,
    },
  };
}

const inter = Inter({ subsets: ["latin"] });
//to get pre rander of data
export default function Home(props) {
  console.log("props:", props);
  const handlerBannerOnClick = () => {
    console.log("Hello to button click");
  };

  return (
    <>
      <Head>
        <title>Harmony Coffee for ev one</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Harmony Cof</h1>
        <Banner
          buttonText="View stores nearby"
          handlerOncClick={handlerBannerOnClick}
        />
        <Image
          className={styles.heroImage}
          src="/assets/icons8-café-64.png"
          width={100}
          height={100}
        ></Image>
        {cofeeshopeData.length < 0 ? (
          <h1>Data not found</h1>
        ) : (
          <div>
            <h2 className={styles.heading2}>Csablanca Stores</h2>
            <div className={styles.cardLayout}>
              {cofeeshopeData.map((items) => {
                return (
                  <CardsOne
                    key={items.id}
                    name={items.name}
                    ImageUrl={items.imgUrl}
                    href={`/coffee-shope/${items.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>

      <footer className={styles.footer}>@Harmony</footer>
    </>
  );
}
